services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    
    container_name: filevault-app
    
    ports:
      - "3000:3000"
    
    environment:
      - NODE_ENV=development

    volumes:
      - .:/usr/src
      - /usr/node_modules
    
    restart: unless-stopped
    
    command: npm run dev
    
networks:
  default:
    name: filevault-network